"""Africa's Talking Voice OTP callback route.

Africa's Talking (AT) calls this endpoint when the recipient answers an
outbound OTP call placed by ``AtVoiceGateway``.  The handler looks up the
OTP stored in Redis and returns an AT XML/JSON action list that instructs
the AT platform to read the digits aloud via TTS then hang up.

Route: GET /voice/otp/{session_id}

This endpoint is intentionally unauthenticated — AT fetches it from its
own servers as part of the outbound call flow.  The session_id is a UUID
generated per-call; it carries no user-identifiable information and the
Redis key expires after 5 minutes.
"""

from __future__ import annotations

import logging

import redis as sync_redis
from fastapi import APIRouter, HTTPException, Path, status
from fastapi.responses import JSONResponse

from app.core.config import settings

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Voice"])

_VOICE_OTP_PREFIX = "voice_otp:"


def _digits_spaced(otp_code: str) -> str:
    """'203153' → '2. 0. 3. 1. 5. 3.' for clear TTS pacing."""
    return ". ".join(otp_code) + "."


@router.get(
    "/voice/otp/{session_id}",
    summary="AT Voice OTP callback",
    description=(
        "Called by Africa's Talking when the recipient answers the OTP call. "
        "Returns AT action JSON that reads the OTP digits aloud then hangs up."
    ),
    response_class=JSONResponse,
    include_in_schema=False,
)
async def voice_otp_callback(
    session_id: str = Path(..., description="UUID generated by AtVoiceGateway"),
) -> JSONResponse:
    """Return AT TTS actions for the OTP voice call."""
    r = sync_redis.from_url(settings.REDIS_URL, decode_responses=True)
    raw = r.get(f"{_VOICE_OTP_PREFIX}{session_id}")
    otp_code: str | None = raw  # type: ignore[assignment]

    if not otp_code:
        logger.warning(
            "voice_otp_callback: session not found or expired — %s", session_id
        )
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="OTP session not found or expired.",
        )

    spaced = _digits_spaced(otp_code)
    message = (
        f"Hello. Your CrisisMap verification code is: {spaced} "
        f"I repeat: {spaced} "
        "Thank you. Goodbye."
    )

    actions = [
        {"say": {"text": message, "voice": "woman", "playBeep": False}},
        {"hangup": {}},
    ]

    logger.info("voice_otp_callback: TTS response sent for session %s", session_id)
    return JSONResponse(content={"actions": actions})
